package lt.oworks.projecteuler.problems;

/**
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 *
 * @author Ovidijus
 */
public class Problem2 extends Problem {

    private static final int LIMIT = 4_000_000;

    @Override
    public String solve() {
        int sum = 0;
        int term = 1;
        int before = 1;
        while (term < LIMIT) {
            sum += (term % 2 == 0) ? term : 0;

            term += before;
            before = term - before;
        }

        return Integer.toString(sum);
    }

}
